// KeepStock domain terminology curated from the team glossary.
// Keep replacements conservative: only normalize phrases that are highly unambiguous.

export const GRAINGER_REP_ROLE_TERMS = Object.freeze([
  "OSR",
  "On Site Representative",
  "OSS",
  "On Site Specialist",
  "AM",
  "Account Manager",
  "KSSC",
  "KeepStock Support Solutions Consultant",
  "MOS",
  "Manager of On-site Services",
  "DSM",
  "District Sales Manager"
]);

const NORMALIZATION_RULES = [
  [/\b(?:keep\s*stock|keeps\s*stock|keep\s*stop|keepstop|keep\s*stake)\b/gi, "KeepStock"],
  [/\b(?:ks\s*web|keep\s*stock\s*web)\b/gi, "KeepStock Web"],
  [/\bkeep\s*stock\s*help\s*desk\b/gi, "KSHD"],
  [/\bcrib\s*master\b/gi, "CribMaster"],
  [/\b(?:gcom|g\s+come)\b/gi, "GCOM"],
  [/\b(?:g\s*vend|grainger\s+vending)\b/gi, "GVEND"],
  [/\bmaintenance\s+request\s+form\b(?!\s*\(MRF\))/gi, "Maintenance Request Form (MRF)"],
  [/\bparts\s+request\s+form\b(?!\s*\(PRF\))/gi, "Parts Request Form (PRF)"],
  [/\be\s*connections\b/gi, "eConnections"],
  [/\bcradle\s*point\b/gi, "Cradlepoint"],
  [/\b(?:molex|mole\s*x|mollex|molly\s+ex)\b/gi, "Molex"],
  [/\bclear\s*spider\b/gi, "ClearSpider"],
  [/\bservice\s*now\b/gi, "ServiceNow"],
  [/\bpower\s*bi\b/gi, "Power BI"],
  [/\badvantage\s*web\b/gi, "AdvantageWeb"],
  [/\bnet\s*cloud\b/gi, "NetCloud"],
  [/\blog\s*me\s*in\s+rescue\b/gi, "LogMeIn Rescue"],
  [/\bon\s+hand\s+balance\b/gi, "On Hand Balance"],
  [/\b(?:r\s*p\s*o)\b/gi, "RPO"],
  [/\b(?:m\s*r\s*f)\b/gi, "MRF"],
  [/\b(?:p\s*r\s*f)\b/gi, "PRF"],
  [/\b(?:i\s*m\s*e\s*i)\b/gi, "IMEI"],
  [/\b(?:r\s*f\s*i\s*d)\b/gi, "RFID"],
  [/\b(?:g\s*f\s*c\s*i)\b/gi, "GFCI"],
  [/\bmac\s+address\b/gi, "MAC Address"],
  [/\broad\s*net\s*id\b/gi, "RoadNetID"],
  [/\b(?:punch\s*out|punchout|pine\s*shot|pineshot|pawn\s*shot|pawnshot)\b/gi, "Punch Out"],
  [/\bpawnshop\s+(?=(?:account|system)\b)/gi, "Punch Out "],
  [/\b(?:jaggaer|jagger)\b/gi, "Jaggaer"],
  [/\b(?:grainger|granger)\s*\.\s*com\b/gi, "Grainger.com"],
  [/\bcurb\s+(?=(?:number|num|#|id)\b)/gi, "crib "]
];

export function normalizeKeepStockTerminology(text) {
  let value = String(text || "");
  for (const [pattern, replacement] of NORMALIZATION_RULES) value = value.replace(pattern, replacement);
  return value;
}

export const DEEPGRAM_KEYTERMS = Object.freeze([
  "KeepStock",
  "KeepStock Web",
  "KSHD",
  "Grainger.com",
  "GCOM",
  "OSR",
  "OSS",
  "KSSC",
  "CribMaster",
  "Epro",
  "GVEND",
  "Crib ID",
  "Program ID",
  "MRF",
  "PRF",
  "Jaggaer",
  "Punch Out",
  "SKU",
  "Unit of Measure",
  "eConnections",
  "RoadNetID",
  "OMS",
  "Cradlepoint",
  "Molex",
  "Badge Reader",
  "RFID",
  "IMEI",
  "GFCI",
  "MAC Address",
  "Power Supply",
  "PSU",
  "Main Board",
  "VMC Circuit Board",
  "Firmware",
  "COM cable",
  "Power BI",
  "AdvantageWeb",
  "NRBA",
  "CMI",
  "VMI",
  "VMV",
  "OKTA",
  "ServiceNow",
  "Job Aid",
  "Microsoft Teams",
  "SNOW",
  "Coil Vending Unit",
  "Locker Vending Unit",
  "Carousel Vending Unit",
  "Drawer Vending Unit",
  "RFIDEAS",
  "ClearSpider",
  "NetCloud",
  "Drop Sensor",
  "Tray",
  "Stop Issue",
  "Stop Order",
  "Badge Only Mode",
  "LogMeIn Rescue",
  "MVE",
  "RPO",
  "Guided Put Away",
  "On Hand Balance",
  "OHB",
  "Storage Unit",
  "Storage Area",
  "Open Stock"
]);
